### GET request to example server
GET localhost:4000/event


### POST request to example server
POST localhost:4000/event
Content-Type: application/json

{
  "description": "Especial de natal",
  "type": 2,
  "date": "2025/12/25",
  "startSales": "20225/10/01",
  "endSales": "2025/12/24",
  "price": 35
}

### GET request to example server
## Necessario informar o UUID do evento valido
GET localhost:4000/event/e9d61365-4fe1-41d7-9efe-b62e50409ac0


### PUT request to example server
## Necessario informar o UUID do evento valido
PUT localhost:4000/event
Content-Type: application/json

{
    "id": "946b164f-a413-49a0-bb8e-c56a8a9b7316",
    "description": "Especial de natal",
    "type": 0,
    "date": "2025/12/25",
    "startSales": "20225/10/01",
    "endSales": "2025/12/25",
    "price": 35.0
}

### DELETE request to example server
## Necessario informar o UUID do evento valido
DELETE localhost:4000/event
Content-Type: application/json

{
  "id": "946b164f-a413-49a0-bb8e-c56a8a9b7316"
}

### GET retorna todas as vendas
GET localhost:4000/sales
###

### POST request to example server
POST localhost:4000/sales
Content-Type: application/json

{
  "user_id": "09f7140d-98a1-408c-bec9-90aa6693d892",
  "event_id": "4ca2be00-e10c-4993-9f7d-c269d08151d6",
  "purchaseDate": "2025/12/29",
  "purchaseStatus": 0
}

### GET request to example server
## Necessario informar o UUID de sales valido
GET localhost:4000/sales/700752be-ab8b-4659-a172-133126eb368a

### PUT request to example server
## Necessario informar o UUID de sales valido
PUT localhost:4000/sales
Content-Type: application/json

{
  "uuid": "183715b7-b1c0-4863-abe8-2a9f03158557",
  "user_id": "09f7140d-98a1-408c-bec9-90aa6693d892",
  "event_id": "4ca2be00-e10c-4993-9f7d-c269d08151d6",
  "purchaseDate": "2026/12/30",
  "purchaseStatus": 3
}

### DELETE request to example server
DELETE localhost:4000/sales
## Necessario informar o UUID de sales valido
Content-Type: application/json

{
  "id": "183715b7-b1c0-4863-abe8-2a9f03158557"
}